drop database if exists BBDD_Cocktails;
create database BBDD_Cocktails;
use BBDD_Cocktails;

drop table if exists drinks;
create table drinks(
	idDrink                     INTEGER  NOT NULL PRIMARY KEY,
	  strDrink                    VARCHAR(6) NOT NULL,
	  strDrinkAlternate           VARCHAR(30),
	  strTags                     VARCHAR(23),
	  strVideo                    VARCHAR(43),
	  strCategory                 VARCHAR(19) NOT NULL,
	  strIBA                      VARCHAR(21),
	  strAlcoholic                VARCHAR(16) NOT NULL,
	  strGlass                    VARCHAR(18) NOT NULL,
	  strInstructions             VARCHAR(450) NOT NULL,
	  strInstructionsES           VARCHAR(138),
	  strInstructionsDE           VARCHAR(516),
	  strInstructionsFR           VARCHAR(30),
	  strInstructionsIT           VARCHAR(453) NOT NULL,
	  strInstructionsZHHANS       VARCHAR(30),
	  strInstructionsZHHANT       VARCHAR(30),
	  strDrinkThumb               VARCHAR(69) NOT NULL,
	  strIngredient1              VARCHAR(19) NOT NULL,
	  strIngredient2              VARCHAR(19) NOT NULL,
	  strIngredient3              VARCHAR(21),
	  strIngredient4              VARCHAR(14),
	  strIngredient5              VARCHAR(11),
	  strIngredient6              VARCHAR(14),
	  strIngredient7              VARCHAR(30),
	  strIngredient8              VARCHAR(30),
	  strIngredient9              VARCHAR(30),
	  strIngredient10             VARCHAR(30),
	  strIngredient11             VARCHAR(30),
	  strIngredient12             VARCHAR(30),
	  strIngredient13             VARCHAR(30),
	  strIngredient14             VARCHAR(30),
	  strIngredient15             VARCHAR(30),
	  strMeasure1                 VARCHAR(17),
	  strMeasure2                 VARCHAR(12),
	  strMeasure3                 VARCHAR(14),
	  strMeasure4                 VARCHAR(9),
	  strMeasure5                 VARCHAR(9),
	  strMeasure6                 VARCHAR(30),
	  strMeasure7                 VARCHAR(30),
	  strMeasure8                 VARCHAR(30),
	  strMeasure9                 VARCHAR(30),
	  strMeasure10                VARCHAR(30),
	  strMeasure11                VARCHAR(30),
	  strMeasure12                VARCHAR(30),
	  strMeasure13                VARCHAR(30),
	  strMeasure14                VARCHAR(30),
	  strMeasure15                VARCHAR(30),
	  strImageSource              VARCHAR(76),
	  strImageAttribution         VARCHAR(63),
	  strCreativeCommonsConfirmed VARCHAR(3) NOT NULL,
	  dateModified                VARCHAR(19) NOT NULL
);
INSERT INTO drinks(idDrink,strDrink,strDrinkAlternate,strTags,strVideo,strCategory,strIBA,strAlcoholic,strGlass,strInstructions,strInstructionsES,strInstructionsDE,strInstructionsFR,strInstructionsIT,strInstructionsZHHANS,strInstructionsZHHANT,strDrinkThumb,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strImageSource,strImageAttribution,strCreativeCommonsConfirmed,dateModified) VALUES (15997,'GG',NULL,NULL,NULL,'Ordinary Drink',NULL,'Optional alcohol','Collins Glass','Pour the Galliano liqueur over ice. Fill the remainder of the glass with ginger ale and thats all there is to it. You now have a your very own GG.',NULL,'Den Galliano-Likör über Eis gießen. Füllen Sie den Rest des Glases mit Ginger Ale und das ist alles, was dazu gehört. Du hast jetzt ein eigenes GG.',NULL,'Versare il liquore Galliano su ghiaccio.
Riempi il resto del bicchiere con ginger ale e questo è tutto.
Ora hai il tuo GG personale.',NULL,NULL,'https://www.thecocktaildb.com/images/media/drink/vyxwut1468875960.jpg','Galliano','Ginger ale','Ice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2 1/2 shots',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'No','2016-07-18 22:06:00');
INSERT INTO drinks(idDrink,strDrink,strDrinkAlternate,strTags,strVideo,strCategory,strIBA,strAlcoholic,strGlass,strInstructions,strInstructionsES,strInstructionsDE,strInstructionsFR,strInstructionsIT,strInstructionsZHHANS,strInstructionsZHHANT,strDrinkThumb,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strImageSource,strImageAttribution,strCreativeCommonsConfirmed,dateModified) VALUES (17222,'A1',NULL,NULL,NULL,'Cocktail',NULL,'Alcoholic','Cocktail glass','Pour all ingredients into a cocktail shaker, mix and serve over ice into a chilled glass.','Vierta todos los ingredientes en una coctelera, mezcle y sirva con hielo en un vaso frío.','Alle Zutaten in einen Cocktailshaker geben, mischen und über Eis in ein gekühltes Glas servieren.',NULL,'Versare tutti gli ingredienti in uno shaker, mescolare e servire con ghiaccio in un bicchiere freddo.',NULL,NULL,'https://www.thecocktaildb.com/images/media/drink/2x8thr1504816928.jpg','Gin','Grand Marnier','Lemon Juice','Grenadine',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1 3/4 shot','1 Shot','1/4 Shot','1/8 Shot',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'No','2017-09-07 21:42:09');
INSERT INTO drinks(idDrink,strDrink,strDrinkAlternate,strTags,strVideo,strCategory,strIBA,strAlcoholic,strGlass,strInstructions,strInstructionsES,strInstructionsDE,strInstructionsFR,strInstructionsIT,strInstructionsZHHANS,strInstructionsZHHANT,strDrinkThumb,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strImageSource,strImageAttribution,strCreativeCommonsConfirmed,dateModified) VALUES (13501,'ABC',NULL,NULL,NULL,'Shot',NULL,'Alcoholic','Shot glass','Layered in a shot glass.','Coloque todos los ingredientes en un vaso de chupito.','Schichtaufbau in einem Schnapsglas.',NULL,'Versa in ordine di lettera i vari ingredienti. 1/3 del bicchiere va riempito con l''Amaretto, 1/3 di Baileys e il restante di Cognac.',NULL,NULL,'https://www.thecocktaildb.com/images/media/drink/tqpvqp1472668328.jpg','Amaretto','Baileys irish cream','Cognac',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1/3','1/3','1/3',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'No','2016-08-31 19:32:08');
INSERT INTO drinks(idDrink,strDrink,strDrinkAlternate,strTags,strVideo,strCategory,strIBA,strAlcoholic,strGlass,strInstructions,strInstructionsES,strInstructionsDE,strInstructionsFR,strInstructionsIT,strInstructionsZHHANS,strInstructionsZHHANT,strDrinkThumb,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strImageSource,strImageAttribution,strCreativeCommonsConfirmed,dateModified) VALUES (17203,'Kir',NULL,'IBA,ContemporaryClassic',NULL,'Ordinary Drink',NULL,'Alcoholic','Wine Glass','Add the crème de cassis to the bottom of the glass, then top up with wine.',NULL,'Gib die Creme de Cassis auf den Boden des Glases und füge dann Wein hinzu.',NULL,'Aggiungere la crème de cassis sul fondo del bicchiere, quindi rabboccare con il vino.',NULL,NULL,'https://www.thecocktaildb.com/images/media/drink/apneom1504370294.jpg','Creme de Cassis','Champagne',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1 part','5 parts',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'No','2017-09-02 17:38:14');
INSERT INTO drinks(idDrink,strDrink,strDrinkAlternate,strTags,strVideo,strCategory,strIBA,strAlcoholic,strGlass,strInstructions,strInstructionsES,strInstructionsDE,strInstructionsFR,strInstructionsIT,strInstructionsZHHANS,strInstructionsZHHANT,strDrinkThumb,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strImageSource,strImageAttribution,strCreativeCommonsConfirmed,dateModified) VALUES (14229,'747',NULL,NULL,NULL,'Shot',NULL,'Alcoholic','Shot glass','pour kaluha, then Baileys, then Frangelico not chilled and not layered -- SERVE!!!',NULL,'Gießen Sie kaluha, dann Baileys, dann Frangelico nicht gekühlt und nicht geschichtet -- SERVE!!!!!!!!',NULL,'Versa Kahlua, Baileys e poi Frangelico.',NULL,NULL,'https://www.thecocktaildb.com/images/media/drink/xxsxqy1472668106.jpg','Kahlua','Baileys irish cream','Frangelico',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1/3 part','1/3 part','1/3 part',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'No','2016-08-31 19:28:26');
INSERT INTO drinks(idDrink,strDrink,strDrinkAlternate,strTags,strVideo,strCategory,strIBA,strAlcoholic,strGlass,strInstructions,strInstructionsES,strInstructionsDE,strInstructionsFR,strInstructionsIT,strInstructionsZHHANS,strInstructionsZHHANT,strDrinkThumb,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strImageSource,strImageAttribution,strCreativeCommonsConfirmed,dateModified) VALUES (15288,'252',NULL,NULL,NULL,'Shot',NULL,'Alcoholic','Shot glass','Add both ingredients to shot glass, shoot, and get drunk quick',NULL,'Beide Zutaten in ein Schnapsglas geben.',NULL,'Aggiungi entrambi gli ingredienti al bicchierino, bevi e ubriacati velocemente',NULL,NULL,'https://www.thecocktaildb.com/images/media/drink/rtpxqw1468877562.jpg','151 proof rum','Wild Turkey',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1/2 shot Bacardi','1/2 shot',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'No','2016-07-18 22:32:42');
INSERT INTO drinks(idDrink,strDrink,strDrinkAlternate,strTags,strVideo,strCategory,strIBA,strAlcoholic,strGlass,strInstructions,strInstructionsES,strInstructionsDE,strInstructionsFR,strInstructionsIT,strInstructionsZHHANS,strInstructionsZHHANT,strDrinkThumb,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strImageSource,strImageAttribution,strCreativeCommonsConfirmed,dateModified) VALUES (17225,'Ace',NULL,NULL,NULL,'Cocktail',NULL,'Alcoholic','Martini Glass','Shake all the ingredients in a cocktail shaker and ice then strain in a cold glass.','Agite todos los ingredientes en una coctelera con hielo y entonces cuélelos sobre un vaso enfriado.','Alle Zutaten in einem Cocktailshaker mit Eis schütteln und dann in einem kalten Glas abseihen.',NULL,'Shakerare tutti gli ingredienti in uno shaker e ghiaccio, quindi filtrare in un bicchiere freddo.',NULL,NULL,'https://www.thecocktaildb.com/images/media/drink/l3cd7f1504818306.jpg','Gin','Grenadine','Heavy cream','Milk','Egg White',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2 shots','1/2 shot','1/2 shot','1/2 shot','1/2 Fresh',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'No','2017-09-07 22:05:06');
INSERT INTO drinks(idDrink,strDrink,strDrinkAlternate,strTags,strVideo,strCategory,strIBA,strAlcoholic,strGlass,strInstructions,strInstructionsES,strInstructionsDE,strInstructionsFR,strInstructionsIT,strInstructionsZHHANS,strInstructionsZHHANT,strDrinkThumb,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strImageSource,strImageAttribution,strCreativeCommonsConfirmed,dateModified) VALUES (17837,'Adam',NULL,'Alcoholic,Holiday',NULL,'Ordinary Drink',NULL,'Alcoholic','Cocktail glass','In a shaker half-filled with ice cubes, combine all of the ingredients. Shake well. Strain into a cocktail glass.','Mezclar todos los ingredientes en una coctelera con cubitos de hielo hasta la mitad. Agitar bien. Colar el contenido en un vaso de cóctel.','In einem Shaker, der halb mit Eiswürfeln gefüllt ist, alle Zutaten vermengen. Gut schütteln. In ein Cocktailglas abseihen.',NULL,'In uno shaker riempito a metà con cubetti di ghiaccio, unire tutti gli ingredienti.Agitare bene.Filtrare in un bicchiere da cocktail.',NULL,NULL,'https://www.thecocktaildb.com/images/media/drink/v0at4i1582478473.jpg','Dark rum','Lemon juice','Grenadine',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2 oz','1 oz','1 tsp',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Yes','2016-09-02 11:29:29');
INSERT INTO drinks(idDrink,strDrink,strDrinkAlternate,strTags,strVideo,strCategory,strIBA,strAlcoholic,strGlass,strInstructions,strInstructionsES,strInstructionsDE,strInstructionsFR,strInstructionsIT,strInstructionsZHHANS,strInstructionsZHHANT,strDrinkThumb,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strImageSource,strImageAttribution,strCreativeCommonsConfirmed,dateModified) VALUES (13332,'B-53',NULL,NULL,NULL,'Shot',NULL,'Alcoholic','Collins Glass','Layer the Kahlua, Sambucca and Grand Marnier into a shot glas in that order. Better than B-52',NULL,'Schichte die Kahlua, Sambucca und Grand Marnier in dieser Reihenfolge in ein Schnapsglas ein. Besser als B-52',NULL,'Metti Kahlua, Sambuca e Grand Marnier in un bicchierino in quest''ordine.',NULL,NULL,'https://www.thecocktaildb.com/images/media/drink/rwqxrv1461866023.jpg','Kahlua','Sambuca','Grand Marnier',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1/3 shot','1/3 shot','1/3 shot',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'No','2016-04-28 18:53:43');
INSERT INTO drinks(idDrink,strDrink,strDrinkAlternate,strTags,strVideo,strCategory,strIBA,strAlcoholic,strGlass,strInstructions,strInstructionsES,strInstructionsDE,strInstructionsFR,strInstructionsIT,strInstructionsZHHANS,strInstructionsZHHANT,strDrinkThumb,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strImageSource,strImageAttribution,strCreativeCommonsConfirmed,dateModified) VALUES (13938,'AT&T',NULL,NULL,NULL,'Ordinary Drink',NULL,'Alcoholic','Highball Glass','Pour Vodka and Gin over ice, add Tonic and Stir','Vierta el vodka y la ginebra sobre el hielo, agregue la tónica y revuelva.','Wodka und Gin über das Eis gießen, Tonic hinzufügen und umrühren.',NULL,'Versare la vodka e il gin sul ghiaccio, aggiungere l''acqua tonica e mescolare',NULL,NULL,'https://www.thecocktaildb.com/images/media/drink/rhhwmp1493067619.jpg','Absolut Vodka','Gin','Tonic water',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1 oz','1 oz','4 oz',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'No','2017-04-24 22:00:19');
INSERT INTO drinks(idDrink,strDrink,strDrinkAlternate,strTags,strVideo,strCategory,strIBA,strAlcoholic,strGlass,strInstructions,strInstructionsES,strInstructionsDE,strInstructionsFR,strInstructionsIT,strInstructionsZHHANS,strInstructionsZHHANT,strDrinkThumb,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strImageSource,strImageAttribution,strCreativeCommonsConfirmed,dateModified) VALUES (14610,'ACID',NULL,NULL,NULL,'Shot',NULL,'Alcoholic','Shot glass','Poor in the 151 first followed by the 101 served with a Coke or Dr Pepper chaser.','Vierta primero el Bacardi 151, seguido del Wild Turkey 101 y sirva con Coca-Cola o Dr Pepper.','Gering den 151 gefolgt von der 101, die mit einer Cola oder Dr. Pepper Chaser serviert wird.',NULL,'Versa prima il Bacardi 151 seguito dal 101, servito con una Coca-Cola.',NULL,NULL,'https://www.thecocktaildb.com/images/media/drink/xuxpxt1479209317.jpg','151 proof rum','Wild Turkey',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1 oz Bacardi','1 oz',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'No','2016-11-15 11:28:37');
INSERT INTO drinks(idDrink,strDrink,strDrinkAlternate,strTags,strVideo,strCategory,strIBA,strAlcoholic,strGlass,strInstructions,strInstructionsES,strInstructionsDE,strInstructionsFR,strInstructionsIT,strInstructionsZHHANS,strInstructionsZHHANT,strDrinkThumb,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strImageSource,strImageAttribution,strCreativeCommonsConfirmed,dateModified) VALUES (15853,'B-52',NULL,'IBA,NewEra',NULL,'Shot','New Era Drinks','Alcoholic','Shot glass','Layer ingredients into a shot glass. Serve with a stirrer.',NULL,'Zutaten in ein Schnapsglas schichten. Mit einem Rührstab servieren.',NULL,'Metti gli ingredienti in un bicchiere da shot a strati.
Servire con una paletta.',NULL,NULL,'https://www.thecocktaildb.com/images/media/drink/5a3vg61504372070.jpg','Baileys irish cream','Grand Marnier','Kahlua',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1/3','1/3','1/4',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'No','2017-09-02 18:07:51');
INSERT INTO drinks(idDrink,strDrink,strDrinkAlternate,strTags,strVideo,strCategory,strIBA,strAlcoholic,strGlass,strInstructions,strInstructionsES,strInstructionsDE,strInstructionsFR,strInstructionsIT,strInstructionsZHHANS,strInstructionsZHHANT,strDrinkThumb,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strImageSource,strImageAttribution,strCreativeCommonsConfirmed,dateModified) VALUES (16262,'H.D.',NULL,NULL,NULL,'Coffee / Tea',NULL,'Alcoholic','Beer mug','Mix the whisky and Baileys Cream in a beer-glass (at least 50 cl). Fill the rest of the glass with coffee.',NULL,'Den Whisky und die Baileys Cream in einem Bierglas (mind. 50 cl) mischen. Füllen Sie den Rest des Glases mit Kaffee.',NULL,'Mescolare il whisky e la crema di Baileys in un bicchiere da birra (almeno 50 cl).
Riempi il resto del bicchiere di caffè.',NULL,NULL,'https://www.thecocktaildb.com/images/media/drink/upusyu1472667977.jpg','Whisky','Baileys irish cream','Coffee',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'4 cl','8 cl',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'No','2016-08-31 19:26:18');
INSERT INTO drinks(idDrink,strDrink,strDrinkAlternate,strTags,strVideo,strCategory,strIBA,strAlcoholic,strGlass,strInstructions,strInstructionsES,strInstructionsDE,strInstructionsFR,strInstructionsIT,strInstructionsZHHANS,strInstructionsZHHANT,strDrinkThumb,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strImageSource,strImageAttribution,strCreativeCommonsConfirmed,dateModified) VALUES (17141,'Smut',NULL,NULL,NULL,'Punch / Party Drink',NULL,'Alcoholic','Beer mug','Throw it all together and serve real cold.',NULL,'Schütte alles zusammen und serviere es kalt.',NULL,'Metti tutto insieme e servi freddo.',NULL,NULL,'https://www.thecocktaildb.com/images/media/drink/rx8k8e1504365812.jpg','Red wine','Peach schnapps','Pepsi Cola','Orange juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1/3 part','1 shot','1/3 part','1/3 part',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'No','2017-09-02 16:23:32');
INSERT INTO drinks(idDrink,strDrink,strDrinkAlternate,strTags,strVideo,strCategory,strIBA,strAlcoholic,strGlass,strInstructions,strInstructionsES,strInstructionsDE,strInstructionsFR,strInstructionsIT,strInstructionsZHHANS,strInstructionsZHHANT,strDrinkThumb,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strImageSource,strImageAttribution,strCreativeCommonsConfirmed,dateModified) VALUES (17208,'Rose',NULL,'IBA,ContemporaryClassic',NULL,'Ordinary Drink','Contemporary Classics','Alcoholic','Cocktail glass','Shake together in a cocktail shaker, then strain into chilled glass. Garnish and serve.',NULL,'In einem Cocktailshaker vermengen und dann in ein gekühltes Glas abseihen. Garnieren und servieren.',NULL,'Shakerare insieme in uno shaker, quindi filtrare in un bicchiere freddo.
Guarnire e servire.',NULL,NULL,'https://www.thecocktaildb.com/images/media/drink/8kxbvq1504371462.jpg','Dry Vermouth','Gin','Apricot brandy','Lemon juice','Grenadine','Powdered sugar',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1/2 oz','1 oz','1/2 oz','1/2 tsp','1 tsp',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'No','2017-09-02 17:57:42');
INSERT INTO drinks(idDrink,strDrink,strDrinkAlternate,strTags,strVideo,strCategory,strIBA,strAlcoholic,strGlass,strInstructions,strInstructionsES,strInstructionsDE,strInstructionsFR,strInstructionsIT,strInstructionsZHHANS,strInstructionsZHHANT,strDrinkThumb,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strImageSource,strImageAttribution,strCreativeCommonsConfirmed,dateModified) VALUES (17833,'A. J.',NULL,NULL,NULL,'Ordinary Drink',NULL,'Alcoholic','Cocktail glass','Shake ingredients with ice, strain into a cocktail glass, and serve.','Agite bien los ingredientes con hielo, cuélelos en una copa de cóctel y sirva.',NULL,NULL,'Shakerare gli ingredienti con ghiaccio, filtrare in una coppetta da cocktail e servire.',NULL,NULL,'https://www.thecocktaildb.com/images/media/drink/l74qo91582480316.jpg','Applejack','Grapefruit juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1 1/2 oz','1 oz',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Yes','2016-09-02 11:16:58');
INSERT INTO drinks(idDrink,strDrink,strDrinkAlternate,strTags,strVideo,strCategory,strIBA,strAlcoholic,strGlass,strInstructions,strInstructionsES,strInstructionsDE,strInstructionsFR,strInstructionsIT,strInstructionsZHHANS,strInstructionsZHHANT,strDrinkThumb,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strImageSource,strImageAttribution,strCreativeCommonsConfirmed,dateModified) VALUES (17187,'Derby',NULL,'Classic,IBA','https://www.youtube.com/watch?v=bYQTTokGkFI','Ordinary Drink','Unforgettables','Alcoholic','Cocktail glass','Pour all ingredients into a mixing glass with ice. Stir. Strain into a cocktail glass. Garnish with a sprig of fresh mint in the drink.',NULL,'Alle Zutaten in ein Mischglas mit Eis geben. Rühren. In ein Cocktailglas abseihen. Mit einem Zweig frischer Minze im Getränk garnieren.',NULL,'Versare tutti gli ingredienti in un mixing glass con ghiaccio. Filtrare in un bicchiere da cocktail. Agitare. Guarnire con un rametto di menta fresca nella bevanda.',NULL,NULL,'https://www.thecocktaildb.com/images/media/drink/52weey1606772672.jpg','gin','Peach Bitters','Mint',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'6 cl','2 dashes','2 Fresh leaves',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'https://commons.wikimedia.org/wiki/File:IBA_Cocktail_Derby_(28968231993).jpg','Michael Styne https://www.flickr.com/photos/mstyne/28968231993/','No','2017-09-02 11:45:56');
INSERT INTO drinks(idDrink,strDrink,strDrinkAlternate,strTags,strVideo,strCategory,strIBA,strAlcoholic,strGlass,strInstructions,strInstructionsES,strInstructionsDE,strInstructionsFR,strInstructionsIT,strInstructionsZHHANS,strInstructionsZHHANT,strDrinkThumb,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strImageSource,strImageAttribution,strCreativeCommonsConfirmed,dateModified) VALUES (12764,'Karsk',NULL,NULL,NULL,'Ordinary Drink',NULL,'Alcoholic','Highball glass','Put a copper coin in a coffe-cup and fill up with coffee until you no longer see the coin, then add alcohol until you see the coin. Norwegian speciality.',NULL,'Legen Sie eine Kupfermünze in eine Kaffeetasse und füllen Sie sie mit Kaffee, bis Sie die Münze nicht mehr sehen, dann fügen Sie Alkohol hinzu, bis Sie die Münze wieder sehen. Norwegische Spezialität.',NULL,'Metti una moneta di rame in una tazza da caffè e riempila di caffè finché non vedi più la moneta, quindi aggiungi l''alcol finché non vedi la moneta. Specialità norvegese.',NULL,NULL,'https://www.thecocktaildb.com/images/media/drink/808mxk1487602471.jpg','Coffee','Grain alcohol',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1 part','2 parts',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'No','2017-02-20 14:54:31');
INSERT INTO drinks(idDrink,strDrink,strDrinkAlternate,strTags,strVideo,strCategory,strIBA,strAlcoholic,strGlass,strInstructions,strInstructionsES,strInstructionsDE,strInstructionsFR,strInstructionsIT,strInstructionsZHHANS,strInstructionsZHHANT,strDrinkThumb,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strImageSource,strImageAttribution,strCreativeCommonsConfirmed,dateModified) VALUES (12776,'Melya',NULL,NULL,NULL,'Coffee / Tea',NULL,'Non alcoholic','Coffee mug','Brew espresso. In a coffee mug, place 1 teaspoon of unsweetened powdered cocoa, then cover a teaspoon with honey and drizzle it into the cup. Stir while the coffee brews, this is the fun part. The cocoa seems to coat the honey without mixing, so you get a dusty, sticky mass that looks as though it will never mix. Then all at once, presto! It looks like dark chocolate sauce. Pour hot espresso over the honey, stirring to dissolve. Serve with cream.',NULL,'Espresso zubereiten. In eine Kaffeetasse 1 Teelöffel ungesüßten, pulverisierten Kakao geben, dann einen Teelöffel Honig in die Tasse träufeln. Rühren Sie um, während der Kaffee brüht, das ist der lustige Teil. Der Kakao scheint den Honig ohne Mischen zu überziehen, so dass Sie eine dichte, klebrige Masse erhalten, die aussieht, als würde sie sich nie vermischen. Dann auf einmal, presto! Es sieht aus wie dunkle Schokoladensoße. Heißen Espresso über den Honig gießen und unter Rühren auflösen. Mit Sahne servieren.',NULL,'Prepara l''espresso.
In una tazza da caffè, mettete 1 cucchiaino di cacao amaro in polvere, quindi coprite un cucchiaino con del miele e versatelo nella tazza.
Mescola mentre il caffè si prepara, questa è la parte divertente.
Il cacao sembra ricoprire il miele senza mescolarsi, quindi si ottiene una massa polverosa e appiccicosa che sembra non si mescolerà mai.
Versare l''espresso caldo sul miele, mescolando per scioglierlo.
Servire con la panna.',NULL,NULL,'https://www.thecocktaildb.com/images/media/drink/xwtptq1441247579.jpg','Espresso','Honey','Cocoa powder',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Unsweetened',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'No','2015-09-03 03:32:59');
INSERT INTO drinks(idDrink,strDrink,strDrinkAlternate,strTags,strVideo,strCategory,strIBA,strAlcoholic,strGlass,strInstructions,strInstructionsES,strInstructionsDE,strInstructionsFR,strInstructionsIT,strInstructionsZHHANS,strInstructionsZHHANT,strDrinkThumb,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strImageSource,strImageAttribution,strCreativeCommonsConfirmed,dateModified) VALUES (14598,'50/50',NULL,NULL,NULL,'Ordinary Drink',NULL,'Alcoholic','Collins Glass','fill glass with crushed ice. Add vodka. Add a splash of grand-marnier. Fill with o.j.',NULL,'Glas mit zerstoßenem Eis füllen. Füge Wodka hinzu. Füge einen Spritzer Grand-Marnier hinzu. Füllen Sie mit o.j.',NULL,'Riempire un bicchiere con ghiaccio tritato.
Aggiungi la vodka.
Aggiungi un tocco di grand-Marnier.
Riempi di succo d''arancia',NULL,NULL,'https://www.thecocktaildb.com/images/media/drink/wwpyvr1461919316.jpg','Vanilla vodka','Grand Marnier','Orange juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2 1/2 oz','1 splash','Fill with',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'No','2016-04-29 09:41:56');
INSERT INTO drinks(idDrink,strDrink,strDrinkAlternate,strTags,strVideo,strCategory,strIBA,strAlcoholic,strGlass,strInstructions,strInstructionsES,strInstructionsDE,strInstructionsFR,strInstructionsIT,strInstructionsZHHANS,strInstructionsZHHANT,strDrinkThumb,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strImageSource,strImageAttribution,strCreativeCommonsConfirmed,dateModified) VALUES (15328,'Zorro',NULL,NULL,NULL,'Coffee / Tea',NULL,'Alcoholic','Coffee Mug','add all and pour black coffee and add whipped cream on top.',NULL,'Alles hinzufügen, schwarzen Kaffee einfüllen und mit Schlagsahne übergießen.',NULL,'Aggiungere il tutto e versare il caffè nero e aggiungere sopra la panna montata.',NULL,NULL,'https://www.thecocktaildb.com/images/media/drink/kvvd4z1485621283.jpg','Sambuca','Baileys irish cream','White Creme de Menthe',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2 cl','2 cl','2 cl',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'No','2017-01-28 16:34:43');
INSERT INTO drinks(idDrink,strDrink,strDrinkAlternate,strTags,strVideo,strCategory,strIBA,strAlcoholic,strGlass,strInstructions,strInstructionsES,strInstructionsDE,strInstructionsFR,strInstructionsIT,strInstructionsZHHANS,strInstructionsZHHANT,strDrinkThumb,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strImageSource,strImageAttribution,strCreativeCommonsConfirmed,dateModified) VALUES (17254,'Bijou',NULL,NULL,NULL,'Cocktail',NULL,'Alcoholic','Cocktail glass','Stir in mixing glass with ice and strain',NULL,'In Mischglas mit Eis verrühren und abseihen.',NULL,'Mescolare nel mixing glass con ghiaccio e filtrare',NULL,NULL,'https://www.thecocktaildb.com/images/media/drink/rysb3r1513706985.jpg','Orange Bitters','Green Chartreuse','Gin','Sweet Vermouth',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1 dash','1 oz','1 oz','1 oz',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'No','2017-12-19 18:09:45');
INSERT INTO drinks(idDrink,strDrink,strDrinkAlternate,strTags,strVideo,strCategory,strIBA,strAlcoholic,strGlass,strInstructions,strInstructionsES,strInstructionsDE,strInstructionsFR,strInstructionsIT,strInstructionsZHHANS,strInstructionsZHHANT,strDrinkThumb,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strImageSource,strImageAttribution,strCreativeCommonsConfirmed,dateModified) VALUES (17839,'Affair',NULL,NULL,NULL,'Ordinary Drink',NULL,'Alcoholic','Highball glass','Pour schnapps, orange juice, and cranberry juice over ice in a highball glass. Top with club soda and serve.','Vierta el Schnapps, el jugo de naranja y el jugo de arándano sobre hielo en un vaso alto. Complete con el agua carbonatada y sirva.','Gießen Sie Schnaps, Orangensaft und Cranberrysaft über Eis in ein Highball-Glas. Mit Club-Soda überziehen und servieren.',NULL,'Versare la grappa, il succo d''arancia e il succo di mirtillo rosso sul ghiaccio in un bicchiere highball. Completare con la soda club e servire.',NULL,NULL,'https://www.thecocktaildb.com/images/media/drink/h5za6y1582477994.jpg','Strawberry schnapps','Orange juice','Cranberry juice','Club soda',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2 oz','2 oz','2 oz',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Yes','2016-09-01 10:05:34');
INSERT INTO drinks(idDrink,strDrink,strDrinkAlternate,strTags,strVideo,strCategory,strIBA,strAlcoholic,strGlass,strInstructions,strInstructionsES,strInstructionsDE,strInstructionsFR,strInstructionsIT,strInstructionsZHHANS,strInstructionsZHHANT,strDrinkThumb,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strImageSource,strImageAttribution,strCreativeCommonsConfirmed,dateModified) VALUES (11149,'Boxcar',NULL,NULL,NULL,'Ordinary Drink',NULL,'Alcoholic','Whiskey sour glass','In a shaker half-filled with ice cubes, combine all of the ingredients. Shake well. Strain into a sour glass.',NULL,'In einem Shaker, der halb mit Eiswürfeln gefüllt ist, alle Zutaten vermengen. Gut schütteln. In ein Sour Glas abseihen.',NULL,'In uno shaker riempito a metà con cubetti di ghiaccio, unire tutti gli ingredienti.Filtrare in un bicchiere sour.Agitare bene.',NULL,NULL,'https://www.thecocktaildb.com/images/media/drink/pwgtpa1504366376.jpg','Gin','Triple sec','Lemon juice','Grenadine','Egg white',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1 1/2 oz','1 oz','1 tsp','1/2 tsp','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'No','2017-09-02 16:32:57');
INSERT INTO drinks(idDrink,strDrink,strDrinkAlternate,strTags,strVideo,strCategory,strIBA,strAlcoholic,strGlass,strInstructions,strInstructionsES,strInstructionsDE,strInstructionsFR,strInstructionsIT,strInstructionsZHHANS,strInstructionsZHHANT,strDrinkThumb,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15,strMeasure1,strMeasure2,strMeasure3,strMeasure4,strMeasure5,strMeasure6,strMeasure7,strMeasure8,strMeasure9,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strImageSource,strImageAttribution,strCreativeCommonsConfirmed,dateModified) VALUES (11872,'Orgasm',NULL,NULL,NULL,'Ordinary Drink',NULL,'Alcoholic','Cocktail glass','Shake all ingredients with ice, strain into a chilled cocktail glass, and serve.',NULL,NULL,NULL,'Shakerare tutti gli ingredienti con ghiaccio, filtrare in una coppetta da cocktail fredda e servire.',NULL,NULL,'https://www.thecocktaildb.com/images/media/drink/vr6kle1504886114.jpg','Creme de Cacao','Amaretto','Triple sec','Vodka','Light cream',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1/2 oz white','1/2 oz','1/2 oz','1/2 oz','1 oz',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'No','2017-09-08 16:55:14');
